### ISSUE TITLE
The monthly cron build of Travis-CI on master fails.

### ISSUE THREAD

**Issue by zhenwendai** [amzn/MXFusion#119]
The monthly cron build of Travis-CI on master branch fails, because it tries to deploy again. Here is the link to a build: https://travis-ci.org/amzn/MXFusion/jobs/453598240.

**Comment by zhenwendai** [comment]
@meissnereric Could you have a look into the issue? Thanks!

**Comment by meissnereric** [comment]
Yeah, will have a look.

**Comment by zhenwendai** [comment]
Resolved.
