### ISSUE TITLE
VAE notebook doesn't run

### ISSUE THREAD

**Issue by marpulli** [amzn/MXFusion#160]
**Describe the bug**
The inference in the VAE notebook fails due to inconsistent shapes somewhere.

**To Reproduce**
Run the VAE notebook with either latest develop or master branch.

**Expected behavior**
It should run

**Desktop (please complete the following information):**
 - OS: osx
 - Python version 3.6
 - MXNet version 1.3.0.post0
 - MXFusion version latest master
 - MXNet context cpu
 - MXNet dtype ?

**Additional context**
Changing the model definition makes it work. After making the following changes, the inference runs:
- Changed m.noise_var shape from (1,) to (1, 1)
- Changed q.x_var shape from (1,) to (1,1)
- Change shape of mean and variance of m.x from (1,) to (1,1)

I guess the question is whether this is a bug in the model definition or whether the inference should work with the model definition unchanged?

**Comment by zhenwendai** [comment]
Thanks @marpulli for pointing this out! The error is due to the changes in 0.3. I will create a pull request to update this notebook in a few ways.

**Comment by zhenwendai** [comment]
The VAE notebook has been updated.
